=== rcabral/upgrade-configuration/source/upgrade-configuration/upgrade-configuration.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="UpgradeConfiguration">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="build">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="steps">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="Step">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="upgrade">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element minOccurs="0" name="path" type="xs:string" />
                                <xs:element minOccurs="0" name="className" type="xs:string" />
                                <xs:element minOccurs="0" name="sql" type="xs:string" />
                              </xs:sequence>
                              <xs:attribute name="class" type="xs:string" use="required" />
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" name="downgrade">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element minOccurs="0" name="path" type="xs:string" />
                                <xs:element minOccurs="0" name="sql" type="xs:string" />
                              </xs:sequence>
                              <xs:attribute name="class" type="xs:string" use="required" />
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="number" type="xs:unsignedByte" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="message" type="xs:string" />
            </xs:sequence>
            <xs:attribute name="majorVersion" type="xs:unsignedByte" use="required" />
            <xs:attribute name="minorVersion" type="xs:unsignedByte" use="required" />
            <xs:attribute name="releaseVersion" type="xs:unsignedByte" use="required" />
            <xs:attribute name="buildNumber" type="xs:unsignedInt" use="required" />
            <xs:attribute name="buildSequence" type="xs:unsignedByte" use="required" />
            <xs:attribute name="downgrade" type="xs:boolean" use="optional" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rcabral/upgrade-configuration/source/upgrade-configuration/demo/upgrade-build/upgrade-configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<UpgradeConfiguration
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="upgrade-configuration.xsd">
	<!-- List of Builds -->
	<build majorVersion="1" minorVersion="0" releaseVersion="0"
		buildNumber="151122" buildSequence="0">
		<!-- List of Steps -->
		<steps>
			<Step number="0">
				<!-- Upgrade Action -->
				<upgrade class="br.puc.rio.model.RunSQLAction">
					<sql>CREATE TABLE MY_FIRST_TABLE(id int(4) AUTO_INCREMENT,name
						varchar(30) NOT NULL,PRIMARY KEY (id));</sql>
				</upgrade>
				<!-- Downgrade Action -->
				<downgrade class="br.puc.rio.model.RunSQLAction">
					<sql>DROP TABLE MY_FIRST_TABLE;</sql>
				</downgrade>
			</Step>
			<Step number="1">
				<!-- Upgrade Action -->
				<upgrade class="br.puc.rio.model.RunSQLAction">
					<sql>CREATE TABLE MY_SECOND_TABLE(id int(4) AUTO_INCREMENT,name
						varchar(30) NOT NULL,PRIMARY KEY (id));</sql>
				</upgrade>
				<!-- Downgrade Action -->
				<downgrade class="br.puc.rio.model.RunSQLAction">
					<sql>DROP TABLE MY_SECOND_TABLE;</sql>
				</downgrade>
			</Step>
		</steps>
		<message>UpgradeConfiguration version 1.0.0.151122</message>
	</build>
	<!-- New Build declaration -->
	<build majorVersion="2" minorVersion="0" releaseVersion="0"
		buildNumber="161122" buildSequence="0">
		<!-- List of Steps -->
		<steps>
			<Step number="0">
				<!-- Upgrade Action -->
				<upgrade class="br.puc.rio.model.RunSQLAction">
					<sql>CREATE TABLE MY_THIRD_TABLE(id int(4) AUTO_INCREMENT,name
						varchar(30) NOT NULL,PRIMARY KEY (id));</sql>
				</upgrade>
				<!-- Downgrade Action -->
				<downgrade class="br.puc.rio.model.RunSQLAction">
					<sql>DROP TABLE MY_THIRD_TABLE;</sql>
				</downgrade>
			</Step>
			<Step number="1">
				<!-- Upgrade Action -->
				<upgrade class="br.puc.rio.model.RunSQLAction">
					<sql>CREATE TABLE FOURTH (id int(4) AUTO_INCREMENT,name
						varchar(30) NOT NULL,PRIMARY KEY (id));</sql>
				</upgrade>
				<!-- Downgrade Action -->
				<downgrade class="br.puc.rio.model.RunSQLAction">
					<sql>DROP TABLE FOURTH ;</sql>
				</downgrade>
			</Step>
		</steps>
		<message>UpgradeConfiguration version 2.0.0.161122</message>
	</build>
</UpgradeConfiguration>
